### ISSUE TITLE
How to hide linenumber without skipping it?

### ISSUE THREAD

**Issue by tweh** [maieul/ledmac#267]
This is mor a feature request than a bug … I wonder how I can hide the number of a verse but actually counting it and be able to use critical notes. Please take a look at the following example:

    \documentclass[a5paper,pagesize]{scrbook}
    \usepackage{eledmac}
    \usepackage{eledpar}
    
    \setstanzaindents{1,0}
    \setcounter{stanzaindentsrepetition}{1}
    \firstlinenum{1}
    \linenumincrement{1}
    
    \newcommand{\hidenumbering}{%
       \skipnumbering
       \advanceline{0}%
    }
    
    \makeatletter
    \newcommand{\hidenumberingII}{%
       \ifledRcol
         \write\linenum@outR{\string\n@num}%
       \else
        \write\linenum@out{\string\n@num}%
       \fi
    }
    \makeatother
    
    \begin{document}
    \begin{pages}
    \begin{Leftside}
        \beginnumbering
        \stanza
        left verse 1.1 &
        left verse 1.2 - H \hidenumbering &
        left verse 1.3 &
        left verse 1.4 &
        left verse 1.5 - H \hidenumbering &
        left verse 1.6 &
        left verse 1.7 - S \skipnumbering &
        left verse 1.8 &
        left verse 1.9 - S \skipnumbering &
        left verse 1.10
        \&
        \stanza
        left verse 2.1 &
        left verse 2.2 - H2 \hidenumberingII &
        left verse 2.3 &
        left verse 2.4 &
        left \edtext{verse 2.5}{\Afootnote{Test it. - H2}}
           - H2 \hidenumberingII &
        left verse 2.6 &
        left verse 2.7 &
        left \edtext{verse 2.8}{\Afootnote{Test it. - H}}
           - H \hidenumbering &
        left verse 2.9 &
        left verse 2.10
        \&
        \endnumbering
    \end{Leftside}
    \begin{Rightside}
    \firstlinenum{1}
    \linenumincrement{1}
        \beginnumbering
        \stanza
        right verse 1.1 &
        right long long long long long long long long long long long 
           long long long long long long long long long long long 
           long long long long long long verse 1.2 - H \hidenumbering &
        right verse 1.3 &
        right verse 1.4 &
        right verse 1.5 - H \hidenumbering &
        right verse 1.6 &
        right long long long long long long long long long long long 
           long long long long long long long long long long long 
           long long long long long long verse 1.7 - S \skipnumbering &
        right verse 1.8 &
        right verse 1.9 - S \skipnumbering &
        right verse 1.10
        \&
        \stanza
        right verse 2.1 &
        right verse 2.2 - H2 \hidenumberingII &
        right verse 2.3 &
        right verse 2.4 &
        right long long long long long long long long long long long 
           long long long long long long long long long long long 
           long long long long long verse  2.5 - H2 \hidenumberingII &
        right verse 2.6 &
        right verse 2.7 &
        right verse 2.8 - H \hidenumbering &
        right verse 2.9 &
        right verse 2.10
        \&
        \endnumbering
    \end{Rightside}
    \Pages 
    \end{pages} 
    \end{document}

Actually both of my definitions `\hidenumberging` (H) and `\hidenumbering` (H2) work to hide the number while leave the number of the following verse correct. Unfortunately there are some things wrong:

1. It is kind of strange that I have to use `\advancenum{0}` instead of `{1}`
1. My solustion/definition makes it impossible to refer to a verse in the critical notes. The ref numbers are _n_ + 2 instead of _n_.
1. The definition of H2 leads to a false indention and counting for the verse following a multiline verse.

(This example was tested with `eledmac` and `eledpar` from branch issue257.)

**Comment by maieul** [comment]
yes, I should add such feature. Indeed, previous skipnumbering was buged and did that! it should be easy.

**Comment by tweh** [comment]
Great. I'm curious what you come up with … let me know if I can help somehow!

**Comment by maieul** [comment]
please, try branch "issue267". Not one important thing : you MUST use \hidenumbering at the begining of  a longverse (because long verse use subline system)

**Comment by tweh** [comment]
thanks, I got no computer for the weekend and will take a look at it on Monday or Tuesday ...

**Comment by maieul** [comment]
not a problem. I have still #265, #264, #234, #214 and #213 to do for the feature release

**Comment by maieul** [comment]
may I ask you again?

**Comment by tweh** [comment]
Sure :-) It’s on my list for today and you’ll have an answer until this evening!

**Comment by maieul** [comment]
perfect ;-)

**Comment by tweh** [comment]
It seems to work unless I use `\skipnumbering`, which causes a strange behavior: The numbers in the margin are correct in any cases but the references in the apparatus are shifted by +1. A second `\skipnumbering` _doesn’t_ change the shift to +2.

You may do the following with the following MWE to see what I mean (note, that the manual numbering of the verses doesn’t correspond to the actual numbers in the margins) …

1. compile the MWE as is with the commented lines:  
_every thing works fine_.
1. uncomment the lines `\skipnumbering TITLE - S &`:  
_notes shifted by +1_.
1. assume that the problem is the first verse and uncomment the lines `pre-title &`:  
_same as before; shift = +1_.
1. uncomment the lines `\skipnumbering right verse 11 - S &`:  
_expecting shift = +2 for note in `verse 14` but it is +1 still_.
1. comment the lines `pre-title &` and `\skipnumbering TITLE - S &`:  
_all notes before `verse 11` are correct; note in `verse 14` is +1_.



    \documentclass[a5paper,pagesize]{scrbook}
    \usepackage{eledmac}
    \usepackage{eledpar}
    
    \setstanzaindents{1,0}  \setcounter{stanzaindentsrepetition}{1}
    \firstlinenum*{1}  \linenumincrement*{1}
    
    \begin{document}
    \begin{pages}
    \begin{Leftside}
    \beginnumbering
       \stanza
    %   pre-title &
    %   \skipnumbering TITLE - S &
       left verse 1 &
       \hidenumbering left \edtext{verse 2 (N)}{\Afootnote{Test it.}} - H &
       left verse 3 &
       left verse 4 &
       \hidenumbering left \edtext{verse 5 (N)}{\Afootnote{Test it.}} - H &
       left verse 6 &
       \hidenumbering left verse 7 - H (only left) &
       left verse 8 &
       left \edtext{verse 9 (N)}{\Afootnote{Test it.}} &
       left verse 10 &
    %   \skipnumbering left verse 11 - S &
       \hidenumbering left verse 12 - H &
       left verse 13 &
       left \edtext{verse 14 (N)}{\Afootnote{Test it.}} &
       left verse 15
       \&
    \endnumbering
    \end{Leftside}
    \begin{Rightside}
    \beginnumbering
       \stanza
    %   pre-title &
    %   \skipnumbering TITLE - S &
       right verse 1 &
       \hidenumbering right long long long long long long long long long
        long long long long long long long long long long long long long
        long long long long long long long verse 2 - H &
       right verse 3 &
       right verse 4 &
       \hidenumbering right verse 5 - H &
       right verse 6 &
       right verse 7 &
       \hidenumbering right verse 8 - H (only right) &
       right verse 9 &
       right verse 10 &
    %   \skipnumbering right verse 11 - S &
       right verse 12 &
       right verse 13 &
       right verse 14 &
       right verse 15
       \&
    \endnumbering
    \end{Rightside}
    \Pages 
    \end{pages} 
    \end{document}

**Comment by tweh** [comment]
Oh … and another thing. `\hidenumbering` hides the next number to be printed, but it would be great if it only hides the number of the verse it is used in. In my real document I use a macro to print titles in the margin and use `\hidenumbering` in the definition to prevent collisions of the title and the number. But actually the increment is 5 so the number must not be hidden every time. My workaround would be to remove `\hidenumbering` from the definition and use it manually.

Long story short: In the following MWE the 10 should be visible …

    \documentclass[a5paper,pagesize]{scrbook}
    \usepackage{eledmac}
    \usepackage{eledpar}
    
    \setstanzaindents{1,0}  \setcounter{stanzaindentsrepetition}{1}
    \firstlinenum*{5}  \linenumincrement*{5}
    
    \begin{document}
    \begin{pages}
    \begin{Leftside}
    \beginnumbering
       \stanza
       left verse 1 &
       left verse 2 &
       left verse 3 &
       left verse 4 &
       left verse 5 &
       left verse 6 &
       \hidenumbering left verse 7 &
       left verse 8 &
       left verse 9 &
       left verse 10
       \&
    \endnumbering
    \end{Leftside}
    \begin{Rightside}
    \beginnumbering
       \stanza
       right verse 1 &
       right verse 2 &
       right verse 3 &
       right verse 4 &
       right verse 5 &
       right verse 6 &
       right verse 7 &
       right verse 8 &
       right verse 9 &
       right verse 10
       \&
    \endnumbering
    \end{Rightside}
    \Pages 
    \end{pages} 
    \end{document}

**Comment by maieul** [comment]
the first problem is not linked to the \hidenumbering, but more to a bug when solving #257. I am looking for it ;-) (see the problem which is still present with 1ea4775)

**Comment by maieul** [comment]
first problem should be solved now.

**Comment by maieul** [comment]
and second problem should be solved too

**Comment by tweh** [comment]
Thanks I’ll take a look at it tomorrow or thursday …

**Comment by tweh** [comment]
Unfortunately it still doesn’t work correct … sorry …

    \documentclass[a5paper,pagesize]{scrbook}
    \usepackage{eledmac}
    \usepackage{eledpar}
    
    \setstanzaindents{1,0}  \setcounter{stanzaindentsrepetition}{1}
    \firstlinenum*{1}  \linenumincrement*{1}
    
    \begin{document}
    \begin{pages}
    \begin{Leftside}
    \beginnumbering
       \stanza
       left verse 1 &
       left \edtext{verse 2 (N)}{\Afootnote{Test it.}} &
       left verse 3 &
       left verse 4 &
       left \edtext{verse 5 (N)}{\Afootnote{Test it.}}
       \&
    \endnumbering
    \end{Leftside}
    \begin{Rightside}
    \beginnumbering
       \stanza
       \hidenumbering right verse 1 &
       \hidenumbering right long long long long long long long long long
       long long long long long long long verse 2 &
       right verse 3 &
       right verse 4 &
       right verse 5
       \&
    \endnumbering
    \end{Rightside}
    \Pages 
    \end{pages} 
    \end{document}

As you can see the rift verses are numbers incorrectly: The numbers are shifted by one because the second line of verse 2 is counted.

**Comment by maieul** [comment]
any feedback?

**Comment by tweh** [comment]
Did you see my comment yesterday?

**Comment by maieul** [comment]
oups, I was thinking have said you "it should be fixed"� but I have not !

So "it should be fixed"

**Comment by tweh** [comment]
Then I’ll check it :-)

**Comment by tweh** [comment]
Hi,

everything works fine now :-) Even the real document with more than 1000 verses seems to have no problems :-) Merci beaucoup!

**Comment by maieul** [comment]
you're welcome
