### ISSUE TITLE
Readme & make

### ISSUE THREAD

**Issue by baem2** [maieul/ledmac#449]
Dear Maieul,

the readme file says:

> Installation
> ============
>
> -   run: `latex reledmac.ins` (which will generate `reledmac.sty`) and
>     `latex reledpar.ins` (which will generate `reledmac.sty`)
> -   move `reledmac.sty` and `reledpar.sty` to a location where LaTeX
>     will find it (for more information on this see the FAQ).
> 
> To generate a second copy of the manual (which is already supplied as a
> PDF file):
> 
> -   run: `make reledmac.pdf && make reledpar.pdf`

Is there a way to make all files, including the examples? I had a look and ran ``make all``, and got this message after it had done a lot:

> make: *** No rule to make target 'Makefile', needed by 'dist'

Running ``make all`` in the examples folder didn't work at all. How is it supposed to work?

**Comment by maieul** [comment]
It was a case problem in not makefile, not existing in my computer. The new master branch should solve it.

**Comment by baem2** [comment]
Cool, thanks! The make runs better now, but there's still a problem, I'll open a new issue.
