### ISSUE TITLE
lineation by page, nested footnote accross two page

### ISSUE THREAD

**Issue by maieul** [maieul/ledmac#749]
Issue can be opened in English or in French (I prefer in French). Please fill this form.
Please open one issue by problem, and not a global issue for multiple problems. 

# Version of reledmac / reledpar (if that is a devellopement version, please precise the branch)
2.26.5
# If this is a newly introduced problem, please indicate the last working version of the package(s)
# Does the problem happen only when combining with some packages?

# Does the problem happens both in parallel typesetting and normal typesetting?
only //
# Description of the problem
When a nested footnote is accross two page, the low level of the nested footnote in the second page has bad line number.
# Minimal Working Example

Please provide a [MWE](http://minimalbeispiel.de/mini-en.html). 
In  case where the problem happens both in parallel typesetting and normal typesetting, please make your MWE in normal typesetting (because your MWE must be _Minimal_). 

```` 
\documentclass{article}
\usepackage[noend,noeledsec,series={A}]{reledmac}
\lineation{page}
\firstlinenum{1}
\linenumincrement{1}
\begin{document}
\beginnumbering
\null
\vskip 41\baselineskip
\pstart
\edtext{%
  \edtext{A}{\Afootnote{first page}}
  LLLorem ipsum dolor amet 
  sit transitorem ipsum dolor amet 
  sit transitorem ipsum dolor amet 
  sit transitLorem ipsum dolor amet 
  sit transit glorian mundi 
  \edtext{a}{\Afootnote{second page}}%
  }{%
  \Afootnote{long}%
  }
\pend
\endnumbering
\end{document}

````

**Comment by maieul** [comment]
1c31e682eedd61a824ec9dee4026cc02036e7073 premier mauvais commit

**Comment by maieul** [comment]
[issue368-bis.pdf](https://github.com/maieul/ledmac/files/1755358/issue368-bis.pdf)
[issue666.pdf](https://github.com/maieul/ledmac/files/1755359/issue666.pdf)

#666 / #368 étaient des problèmes

**Comment by maieul** [comment]
Le problème:
- dans le commit 1c31e682eedd61a824ec9dee4026cc02036e7073, ligne 6146-6147 on a ajout un \global
- du coup le test `\ifnum #1=\last@page@num` l. 6139 plante lorsqu'on a des edtext imbriqués
  - On pourrait contourner cela en modifiant encore cette fonction pour gérer différement le compteur de ligne, mais on aurait des problèmes pour le faire de manière propre, pour que chaque niveau de edtext fonctionne
  - En plus, c'est peut être mettre quelque chose sous le tapis, parce que le tests de la ligne 6139 est prévu pour réussi si effectivement on n'a pas de changement de page depuis le précédent edtext, quelqusoit la profondeur des edtext.
- Par conséquent, il faut revenir sur ce problème. Il faut simplement stocker temporaireemnt page@num dans un compteur global, qui sert uniquement à cela, lequel compteur sera ensuite transféré globalement sur pahge@num après le \endnumbering (vrai but de 1c31e68 )

[reledmac.sty.zip](https://github.com/maieul/ledmac/files/1755426/reledmac.sty.zip)

**Comment by maieul** [comment]
Voir aussi  194b460fbc37995a78ee34049c167a0391ddc4d9 qui avait modifié sur next@page@num.

**Comment by maieul** [comment]
@ndlecic   @Doc73 : could you try the branch issue749. If fix a bug, which was introduced by some needs for `continuousnumberingwithcolumns`. Could you try this branch does not break anything depending of page number, so:
- anything related to the way `\lineation{page}` , when using `continuousnumberingwithcolumns`
- anything related to sidenote depending of the current page, when using `continuousnumberingwithcolumns`

**Comment by Doc73** [comment]
@maieul 
Stock reledmac v. 2.26.5 has no issues, at least in my book, where I use `continuousnumberingwithcolumns` option.

**Comment by maieul** [comment]
I don't ask for v2.26.5 but for branch issue749, which is under development.

**Comment by Doc73** [comment]
With branch issue749 there are issues: line numbering doesn't continue from the previous page.

**Comment by maieul** [comment]
WHat happens with the new version of the branch? If you have still the issues, could you provide a MWE?

**Comment by federico9996** [comment]
I'm the one who signalled the issue: now everything works properly in my files. If further problems with line-numbering come up during my work, I'll tell you promptly.
Thank you very much for helping.

**Comment by maieul** [comment]
@federico9996. At which hour did you do it? Because I have send some
modification to the branch few minutes ago, and I would like to be sur
you have test the good one.

I am waiting from @doc73 feedback, and if all is ok for your both, I
will publish it quickly on CTAN. If not, I will do modification, and aks
to both of you to test again.

**Comment by Doc73** [comment]
No, same issues with line numbering and side notes.
I can't prepare for now the MWE, because I'm very busy. Please, give me some time.

**Comment by maieul** [comment]
ok,
but when do you think to have time?

**Comment by maieul** [comment]
or please send me directly be email the example which does not work. I
would not publish.
It is not a problem if it not minimal. What I need is to fix quickly
#749, because it is a very important bug.

**Comment by Doc73** [comment]
Done! By mail I've sent to you one of my chapters.
There are several issues in line numbering, starting from pag. 4

**Comment by federico9996** [comment]
To be sure, I've loaded the branch once again and it still doesn't give any problem in my text: I've got no sidenotes and the line numbering is ok (within a five-page-long text)

**Comment by maieul** [comment]
yes, but Indeed there is a bug for @doc73.
I become crazy

**Comment by federico9996** [comment]
There's a little thing I hadn't noticed and I don't actually know whether it's important: the first footnote of the nested macro, namely the one which appears on the first-page apparatus, is printed together with the indication of the page number, so like: 1.29-2.1

**Comment by maieul** [comment]
That is a feature, not a bug. It is to make clear of which line you are speaking.

Suppose a critical note starting on l. 3 of page 1 and finishing on line 4 of page 2. If we don't precise page number, we would have "3-4", and we could think its from line 3 of page 1 to  line 4 of page 1

**Comment by maieul** [comment]
In anyway, it seems the problem of @Doc7 3 was related to some instable files (e.g that change of page break at each run),  I may wait for this answer, and I will publish it wenesday if  @ndlecic

**Comment by Doc73** [comment]
@maieul I did some testes on my book and all seems working very well!

**Comment by maieul** [comment]
I am currently publishing the new version on CTAN.
